dist: xenial
language: node_js
cache: yarn
node_js:
- '6'
- '8'
- '10'
- '11'
before_install:
# Required due to: https://github.com/travis-ci/travis-ci/issues/7951
- curl -sSfL https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn --frozen-lockfile
script:
- yarn lint
- yarn test
